-- MySQL Script generated by MySQL Workbench
-- Fri May 29 18:17:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pizza` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ingredient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cout` FLOAT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`IngredientPizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`IngredientPizza` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantite` INT NOT NULL,
  `Pizza_id` INT NOT NULL,
  `Ingredient_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_IngredientPizza_Pizza_idx` (`Pizza_id` ASC),
  INDEX `fk_IngredientPizza_Ingredient1_idx` (`Ingredient_id` ASC),
  CONSTRAINT `fk_IngredientPizza_Pizza`
    FOREIGN KEY (`Pizza_id`)
    REFERENCES `mydb`.`Pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IngredientPizza_Ingredient1`
    FOREIGN KEY (`Ingredient_id`)
    REFERENCES `mydb`.`Ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pizzeria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pizzeria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `marge` FLOAT NOT NULL,
  `numTelephone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pizzaiolo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pizzaiolo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `numeroSecu` VARCHAR(45) NOT NULL,
  `Pizzeria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pizzaiolo_Pizzeria1_idx` (`Pizzeria_id` ASC),
  CONSTRAINT `fk_Pizzaiolo_Pizzeria1`
    FOREIGN KEY (`Pizzeria_id`)
    REFERENCES `mydb`.`Pizzeria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `Pizza` INT NOT NULL,
  `Pizzeria` INT NOT NULL,
  PRIMARY KEY (`Pizza`, `Pizzeria`),
  INDEX `fk_Pizza_has_Pizzeria_Pizzeria1_idx` (`Pizzeria` ASC),
  INDEX `fk_Pizza_has_Pizzeria_Pizza1_idx` (`Pizza` ASC),
  CONSTRAINT `fk_Pizza_has_Pizzeria_Pizza1`
    FOREIGN KEY (`Pizza`)
    REFERENCES `mydb`.`Pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pizza_has_Pizzeria_Pizzeria1`
    FOREIGN KEY (`Pizzeria`)
    REFERENCES `mydb`.`Pizzeria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
